version: "3.9"
services:
  api:
    build: ./apps/api
    container_name: seo-api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
      - ./data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  web:
    build: ./apps/web
    container_name: seo-web
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    command: sh -c "npm install && npm run dev"
