from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

def generate_pdf_bytes(domain: str, score, summary: str) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(f"SEO Report - {domain}")
    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, 800, f"SEO Report for {domain}")
    c.setFont("Helvetica", 12)
    c.drawString(72, 775, f"Overall Score: {score}")
    text = c.beginText(72, 750)
    text.setFont("Helvetica", 11)
    for line in summary.splitlines() or ["Generated by Seo Analyzer"]:
        text.textLine(line[:110])
    c.drawText(text)
    c.showPage()
    c.save()
    return buf.getvalue()
